DROP TABLE usertest;
CREATE TABLE usertest (id int NOT NULL AUTO_INCREMENT COMMENT 'ID', username varchar(100) NOT NULL COMMENT '名称', sex varchar(100) COMMENT '姓名', city varchar(100) COMMENT '城市', sign varchar(64) COMMENT '签名', experience varchar(64) COMMENT '积分', socre varchar(64) COMMENT '分数', classify varchar(64) COMMENT '职业', wealth varchar(64) COMMENT '财富', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户测试表';
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (1, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (2, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (3, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (4, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (5, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (6, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (7, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (8, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (9, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (10, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (11, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
INSERT INTO usertest (id, username, sex, city, sign, experience, socre, classify, wealth) VALUES (12, '001', '男', '唐山', '10', '20', '36', 'IT', '100');
